namespace Daedalus.Core.Tiled.Tests;

public static class Content {
    public const string SimpleGraph = 
        """
        {
            "label": "my-simple",
            "rooms": [
                { "number": 1, "definition": "entrance" },
                { "number": 2, "definition": "normal" }
            ],
            "connections": [
                { "from": 1, "to": 2, "one-way": true}
            ]
        }
        """;

    public const string SimpleLoopGraph = 
        """
        {
            "label": "simple-loop",
            "rooms": [
                    { "number": 0, "definition": "entrance" },
                    { "number": 1, "definition": "normal" },
                    { "number": 2, "definition": "normal" },
                    { "number": 3, "definition": "exit" }
            ],

            "connections": [
                    { "from": 0, "to": 1 },
                    { "from": 1, "to": 2 },
                    { "from": 2, "to": 3 }
            ]
        }
        """;

    public const string RoomBlueprints = 
        """
        [
            {
                "label": "small-square-1",
                "points": [
                    [0, 0],
                    [0, 5],
                    [5, 5],
                    [5, 0]
                ],
                "compatible-tilemaps": [
                    "s-sq-desert-1"         
                ]},
            {
                "label": "large-square-1",
                "shape": [
                    [0, 0],
                    [0, 5],
                    [5, 5],
                    [5, 0]
                ],
                "compatible-tilemaps": [
                    "s-sq-desert-1"         
                ]
            }
        ]
        """;

        public const string RoomDefinitions = 
        """
        [
            {
                "label": "entrance",
                "type": "Entrance",
                "blueprints": [
                    "small-square-1"
                ]
            },
            {
                "label": "normal",
                "type": "Normal",
                "blueprints": [
                    "small-square-1",
                    "large-square-1"
                ]
            }
        ]
        """;

    public const string TileMapTemplate = 
        """
        { 
            "compressionlevel":-1,
            "height":5,
            "infinite":false,
            "layers":[
                    {
                        "data":[1, 2, 2, 2, 3,
                            9, 10, 10, 10, 11,
                            9, 10, 10, 10, 11,
                            9, 10, 10, 10, 11,
                            17, 18, 18, 18, 19],
                        "height":5,
                        "id":1,
                        "name":"Tile Layer 1",
                        "opacity":1,
                        "type":"tilelayer",
                        "visible":true,
                        "width":5,
                        "x":0,
                        "y":0
                    }],
            "nextlayerid":4,
            "nextobjectid":15,
            "orientation":"orthogonal",
            "renderorder":"right-down",
            "tiledversion":"1.8.5",
            "tileheight":32,
            "tilesets":[
                    {
                    "firstgid":1,
                    "source":"tilesets/s-sq-desert-1.tileset.json"
                    }],
            "tilewidth":32,
            "type":"map",
            "version":"1.8",
            "width":5
        }
        """;
    public const string TileMapTemplateWithObjects = 
        """
        { 
            "compressionlevel":-1,
            "height":5,
            "infinite":false,
            "layers":[
                    {
                        "data":[1, 2, 2, 2, 3,
                            9, 10, 10, 10, 11,
                            9, 10, 10, 10, 11,
                            9, 10, 10, 10, 11,
                            17, 18, 18, 18, 19],
                        "height":5,
                        "id":1,
                        "name":"Tile Layer 1",
                        "opacity":1,
                        "type":"tilelayer",
                        "visible":true,
                        "width":5,
                        "x":0,
                        "y":0
                    },
                    {
                        "id":6,
                        "layers":[
                        {
                        "draworder":"topdown",
                        "id":5,
                        "name":"Object Layer 1",
                        "objects":[
                                {
                                "height":0,
                                "id":1,
                                "name":"",
                                "point":true,
                                "properties":[
                                        {
                                        "name":"EnemyHealth",
                                        "type":"string",
                                        "value":"100"
                                        }, 
                                        {
                                        "name":"ObjectId",
                                        "type":"int",
                                        "value":"1"
                                        }, 
                                        {
                                        "name":"ObjectType",
                                        "type":"string",
                                        "value":"enemy"
                                        }, 
                                        {
                                        "name":"Type",
                                        "type":"string",
                                        "value":"spawn"
                                        }],
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":0,
                                "x":208,
                                "y":146
                                }, 
                                {
                                "height":18,
                                "id":3,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":20,
                                "x":225,
                                "y":49
                                }, 
                                {
                                "ellipse":true,
                                "height":26,
                                "id":4,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":25,
                                "x":114,
                                "y":45
                                }, 
                                {
                                "height":0,
                                "id":5,
                                "name":"",
                                "polygon":[
                                        {
                                        "x":0,
                                        "y":0
                                        }, 
                                        {
                                        "x":23,
                                        "y":30
                                        }, 
                                        {
                                        "x":-8,
                                        "y":31
                                        }],
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":0,
                                "x":66,
                                "y":131
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        }],
                        "name":"Group 1",
                        "opacity":1,
                        "type":"group",
                        "visible":true,
                        "x":0,
                        "y":0
                        }],
            "nextlayerid":4,
            "nextobjectid":15,
            "orientation":"orthogonal",
            "renderorder":"right-down",
            "tiledversion":"1.8.5",
            "tileheight":32,
            "tilesets":[
                    {
                    "firstgid":1,
                    "source":"tilesets/s-sq-desert-1.tileset.json"
                    }],
            "tilewidth":32,
            "type":"map",
            "version":"1.8",
            "width":5
        }
        """;

        public const string TileSetTemplate = 
        """
        { 
            "columns":8,
            "image":"..\/tmw_desert_spacing.png",
            "imageheight":199,
            "imagewidth":265,
            "margin":1,
            "name":"desert",
            "spacing":1,
            "tilecount":48,
            "tiledversion":"1.8.5",
            "tileheight":32,
            "tiles":[
                    {
                    "id":0,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":16.8421,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":15.7255,
                                "x":16.0047,
                                "y":15.0741
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":1,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":16.1814,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":32,
                                "x":0,
                                "y":15.8186
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":2,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":0,
                                "id":2,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":0.0930503,
                                "x":10.2355,
                                "y":22.0529
                                }, 
                                {
                                "height":16.9352,
                                "id":4,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":16.2838,
                                "x":0.0930503,
                                "y":15.0741
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":3,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":4,
                    "properties":[
                            {
                            "name":"Direction",
                            "type":"string",
                            "value":"East"
                            }, 
                            {
                            "name":"IsFirstDoor",
                            "type":"string",
                            "value":"true"
                            }, 
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Door"
                            }]
                    }, 
                    {
                    "id":5,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":6,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":7,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":8,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":32,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":16.375,
                                "x":15.625,
                                "y":0
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":9,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":10,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":32,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":16.375,
                                "x":0,
                                "y":0
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":11,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":12,
                    "properties":[
                            {
                            "name":"Direction",
                            "type":"string",
                            "value":"East"
                            }, 
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Door"
                            }]
                    }, 
                    {
                    "id":13,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":14,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":15,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":16,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":17,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":16.25,
                                "x":15.75,
                                "y":0
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":17,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":16.875,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":32,
                                "x":0,
                                "y":0
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":18,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":17.25,
                                "id":1,
                                "name":"",
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":16,
                                "x":0,
                                "y":0
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":19,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":20,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":21,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":22,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":23,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":24,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":25,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":26,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":27,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":28,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":29,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":30,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":31,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":32,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":33,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":34,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Floor"
                            }]
                    }, 
                    {
                    "id":35,
                    "properties":[
                            {
                            "name":"Direction",
                            "type":"string",
                            "value":"North"
                            }, 
                            {
                            "name":"IsFirstDoor",
                            "type":"string",
                            "value":"true"
                            }, 
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Door"
                            }]
                    }, 
                    {
                    "id":36,
                    "properties":[
                            {
                            "name":"Direction",
                            "type":"string",
                            "value":"North"
                            }, 
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Door"
                            }]
                    }, 
                    {
                    "id":37,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":38,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":39,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":40,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":41,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":42,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Wall"
                            }]
                    }, 
                    {
                    "id":43,
                    "properties":[
                            {
                            "name":"Direction",
                            "type":"string",
                            "value":"North"
                            }, 
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Door"
                            }]
                    }, 
                    {
                    "id":44,
                    "properties":[
                            {
                            "name":"Direction",
                            "type":"string",
                            "value":"North"
                            }, 
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Door"
                            }]
                    }, 
                    {
                    "id":45,
                    "objectgroup":
                        {
                        "draworder":"index",
                        "id":2,
                        "name":"",
                        "objects":[
                                {
                                "height":0,
                                "id":1,
                                "name":"",
                                "polygon":[
                                        {
                                        "x":1.5,
                                        "y":-4.75
                                        }, 
                                        {
                                        "x":-7,
                                        "y":2.875
                                        }, 
                                        {
                                        "x":-6.75,
                                        "y":14.625
                                        }, 
                                        {
                                        "x":0.125,
                                        "y":10.5
                                        }, 
                                        {
                                        "x":0.375,
                                        "y":24.625
                                        }, 
                                        {
                                        "x":7.375,
                                        "y":23.875
                                        }, 
                                        {
                                        "x":7.25,
                                        "y":8.875
                                        }, 
                                        {
                                        "x":15.125,
                                        "y":4.5
                                        }, 
                                        {
                                        "x":15.125,
                                        "y":-4.5
                                        }],
                                "rotation":0,
                                "type":"",
                                "visible":true,
                                "width":0,
                                "x":11.375,
                                "y":4.875
                                }],
                        "opacity":1,
                        "type":"objectgroup",
                        "visible":true,
                        "x":0,
                        "y":0
                        },
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":46,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }, 
                    {
                    "id":47,
                    "properties":[
                            {
                            "name":"Type",
                            "type":"string",
                            "value":"Object"
                            }]
                    }],
            "tilewidth":32,
            "type":"tileset",
            "version":"1.8",
            "wangsets":[
                    {
                    "colors":[
                            {
                            "color":"#ff0000",
                            "name":"Sand",
                            "probability":1,
                            "tile":-1
                            }, 
                            {
                            "color":"#00ff00",
                            "name":"Cobblestone",
                            "probability":1,
                            "tile":-1
                            }, 
                            {
                            "color":"#0000ff",
                            "name":"Pavement",
                            "probability":1,
                            "tile":-1
                            }, 
                            {
                            "color":"#ff7700",
                            "name":"Dirt",
                            "probability":1,
                            "tile":-1
                            }],
                    "name":"Desert Ground",
                    "tile":-1,
                    "type":"corner",
                    "wangtiles":[
                            {
                            "tileid":0,
                            "wangid":[0, 1, 0, 2, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":1,
                            "wangid":[0, 1, 0, 2, 0, 2, 0, 1]
                            }, 
                            {
                            "tileid":2,
                            "wangid":[0, 1, 0, 1, 0, 2, 0, 1]
                            }, 
                            {
                            "tileid":3,
                            "wangid":[0, 4, 0, 1, 0, 4, 0, 4]
                            }, 
                            {
                            "tileid":4,
                            "wangid":[0, 4, 0, 4, 0, 1, 0, 4]
                            }, 
                            {
                            "tileid":5,
                            "wangid":[0, 1, 0, 4, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":6,
                            "wangid":[0, 1, 0, 4, 0, 4, 0, 1]
                            }, 
                            {
                            "tileid":7,
                            "wangid":[0, 1, 0, 1, 0, 4, 0, 1]
                            }, 
                            {
                            "tileid":8,
                            "wangid":[0, 2, 0, 2, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":9,
                            "wangid":[0, 2, 0, 2, 0, 2, 0, 2]
                            }, 
                            {
                            "tileid":10,
                            "wangid":[0, 1, 0, 1, 0, 2, 0, 2]
                            }, 
                            {
                            "tileid":11,
                            "wangid":[0, 1, 0, 4, 0, 4, 0, 4]
                            }, 
                            {
                            "tileid":12,
                            "wangid":[0, 4, 0, 4, 0, 4, 0, 1]
                            }, 
                            {
                            "tileid":13,
                            "wangid":[0, 4, 0, 4, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":14,
                            "wangid":[0, 4, 0, 4, 0, 4, 0, 4]
                            }, 
                            {
                            "tileid":15,
                            "wangid":[0, 1, 0, 1, 0, 4, 0, 4]
                            }, 
                            {
                            "tileid":16,
                            "wangid":[0, 2, 0, 1, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":17,
                            "wangid":[0, 2, 0, 1, 0, 1, 0, 2]
                            }, 
                            {
                            "tileid":18,
                            "wangid":[0, 1, 0, 1, 0, 1, 0, 2]
                            }, 
                            {
                            "tileid":19,
                            "wangid":[0, 2, 0, 1, 0, 2, 0, 2]
                            }, 
                            {
                            "tileid":20,
                            "wangid":[0, 2, 0, 2, 0, 1, 0, 2]
                            }, 
                            {
                            "tileid":21,
                            "wangid":[0, 4, 0, 1, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":22,
                            "wangid":[0, 4, 0, 1, 0, 1, 0, 4]
                            }, 
                            {
                            "tileid":23,
                            "wangid":[0, 1, 0, 1, 0, 1, 0, 4]
                            }, 
                            {
                            "tileid":24,
                            "wangid":[0, 1, 0, 3, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":25,
                            "wangid":[0, 1, 0, 3, 0, 3, 0, 1]
                            }, 
                            {
                            "tileid":26,
                            "wangid":[0, 1, 0, 1, 0, 3, 0, 1]
                            }, 
                            {
                            "tileid":27,
                            "wangid":[0, 1, 0, 2, 0, 2, 0, 2]
                            }, 
                            {
                            "tileid":28,
                            "wangid":[0, 2, 0, 2, 0, 2, 0, 1]
                            }, 
                            {
                            "tileid":29,
                            "wangid":[0, 1, 0, 1, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":32,
                            "wangid":[0, 3, 0, 3, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":33,
                            "wangid":[0, 3, 0, 3, 0, 3, 0, 3]
                            }, 
                            {
                            "tileid":34,
                            "wangid":[0, 1, 0, 1, 0, 3, 0, 3]
                            }, 
                            {
                            "tileid":35,
                            "wangid":[0, 3, 0, 1, 0, 3, 0, 3]
                            }, 
                            {
                            "tileid":36,
                            "wangid":[0, 3, 0, 3, 0, 1, 0, 3]
                            }, 
                            {
                            "tileid":40,
                            "wangid":[0, 3, 0, 1, 0, 1, 0, 1]
                            }, 
                            {
                            "tileid":41,
                            "wangid":[0, 3, 0, 1, 0, 1, 0, 3]
                            }, 
                            {
                            "tileid":42,
                            "wangid":[0, 1, 0, 1, 0, 1, 0, 3]
                            }, 
                            {
                            "tileid":43,
                            "wangid":[0, 1, 0, 3, 0, 3, 0, 3]
                            }, 
                            {
                            "tileid":44,
                            "wangid":[0, 3, 0, 3, 0, 3, 0, 1]
                            }]
                    }]
            }
        """;
}